# Workflow to convert the given FML to Python using MaLaC-HD

name: Convert and validate test file

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  convert-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update pip
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Install MaLaC-HD
        run: |
          git clone https://gitlab.com/cdehealth/malac/models.git
          pip install -e models/fhir
          pip install -e models/cda
          git clone https://gitlab.com/cdehealth/malac/utils.git
          pip install -e utils
          git clone https://gitlab.com/cdehealth/malac/transformer.git
          pip install -e transformer/fhir
          git clone -b cda2fhir_myhealtheu https://gitlab.com/cdehealth/malac-hd.git
          pip install -e malac-hd

      - name: Run MaLaC-HD
        run: |
          malac-hd -m maps/CdaToBundle.4.map -co python-maps/CdaToBundle.4.py

      - name: Download FHIR validator
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: hapifhir/org.hl7.fhir.core
          tag: 'latest'
          path: .
          file: validator_cli.jar

      - name: Download eHDSI Laboratory IG
        run: |
          wget https://fhir.ehdsi.eu/laboratory/package.tgz

      - name: Convert & validate test file to FHIR XML and JSON
        run: |
          mkdir coverage
          mkdir output
          mkdir validation
          for filename in input/*.xml; do
              basename=$(basename "$filename" .xml)
              coverage run --source=python-maps --data-file=coverage/.coverage.xml.$basename --branch python-maps/CdaToBundle.4.py -s $filename -t output/$basename.xml
              coverage run --source=python-maps --data-file=coverage/.coverage.json.$basename --branch python-maps/CdaToBundle.4.py -s $filename -t output/$basename.json
              java -jar validator_cli.jar output/$basename.xml -locale de-AT -version 4.0 -ig package.tgz -html-output validation/$basename.xml.html -show-message-ids -allow-example-urls true -advisor-file advisor.json -extension any > validation/$basename.xml.log || echo "validation errors in FHIR XML"
              java -jar validator_cli.jar output/$basename.json -locale de-AT -version 4.0 -ig package.tgz -html-output validation/$basename.json.html -show-message-ids -allow-example-urls true -advisor-file advisor.json -extension any > validation/$basename.json.log || echo "validation errors in FHIR JSON"
          done

      - name: coverage
        run: |
          coverage combine --keep --data-file=coverage/.coverage coverage/
          coverage xml --data-file=coverage/.coverage -o coverage/coverage.xml
          coverage html --data-file=coverage/.coverage

      - name: display coverage
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          include-hidden-files: true
          path: |
            coverage/
            output/
            validation/
            python-maps/CdaToBundle.4.py
            htmlcov/

      - name: Validate
        run: |
          chmod 744 check_validation_result.sh
          ./check_validation_result.sh || exit_code=$?
          exit $exit_code
