# Workflow to convert the given FML to Python using MaLaC-HD

name: Update ELGA GitLab based on release

on:
  release:
    types: [ released ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install requests

      - name: Create MR in ELGA repository
        run: |
          python scripts/update_elga.py